import ayam from '../assets/content/ayam.jpeg';

export const table = [
  {
    id: 1,
    name: 'A1',
    guess: 4,
    floor: 1,
    status: true,
    // true : reservasi false: available
  },
  {
    id: 2,
    name: 'A2',
    guess: 2,
    floor: 1,
    status: false,
  },
  {
    id: 3,
    name: 'A3',
    guess: 4,
    floor: 1,
    status: true,
  },
  {
    id: 4,
    name: 'A4',
    guess: 4,
    floor: 1,
    status: false,
  },
  {
    id: 5,
    name: 'A5',
    guess: 4,
    floor: 2,
    status: false,
  },
  {
    id: 6,
    name: 'A6',
    guess: 4,
    floor: 2,
    status: false,
  },
];

export const table2 = [
  {
    id: 1,
    name: 'B1',
    guess: 4,
    floor: 1,
    status: true,
    // true : reservasi false: available
  },
  {
    id: 2,
    name: 'B2',
    guess: 2,
    floor: 1,
    status: false,
  },
  {
    id: 3,
    name: 'B3',
    guess: 4,
    floor: 1,
    status: false,
  },
  {
    id: 4,
    name: 'B4',
    guess: 4,
    floor: 1,
    status: false,
  },
  {
    id: 5,
    name: 'B5',
    guess: 4,
    floor: 2,
    status: false,
  },
  {
    id: 6,
    name: 'B6',
    guess: 4,
    floor: 2,
    status: false,
  },
];

export const product = [
  {
    id: 1,
    img: { ayam },
    name: 'chicken wings',
    category: 'food',
    category_code: 'F',
    cabe: 3,
    price: 30000,
    total: 30000,
  },
  {
    id: 2,
    img: '../assets/content/ayam.jpeg',
    name: 'nasi bakar',
    category: 'food',
    category_code: 'F',
    cabe: 2,
    price: 20000,
    total: 20000,
  },
  {
    id: 3,
    img: '../assets/content/ayam.jpeg',
    name: 'Es teh',
    category: 'drink',
    category_code: 'D',
    cabe: 0,
    price: 15000,
    total: 15000,
  },
  {
    id: 4,
    img: '../assets/content/ayam.jpeg',
    name: 'kopi',
    category: 'drink',
    category_code: 'D',
    cabe: 0,
    price: 50000,
    total: 50000,
  },
  {
    id: 5,
    img: '../assets/content/ayam.jpeg',
    name: 'dessert 1',
    category: 'dessert',
    category_code: 'DS',
    cabe: 0,
    price: 50000,
    total: 50000,
  },
  {
    id: 6,
    img: '../assets/content/ayam.jpeg',
    name: 'dessert 2',
    category: 'dessert',
    category_code: 'DS',
    cabe: 0,
    price: 50000,
    total: 50000,
  },
  {
    id: 7,
    img: { ayam },
    name: 'americano',
    category: 'drink',
    category_code: 'D',
    cabe: 3,
    price: 30000,
    total: 30000,
  },
];
